name: Build and Deploy Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Upgrade pip and install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools sphinx

      - name: Install package minimally
        run: pip install --no-deps -e .

      - name: Patch docs conf
        run: sed -i '/from lbm_suite2p_python import __version__/ s/^/#/' docs/conf.py

      - name: Build Docs
        working-directory: docs
        run: make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/_build/html
